/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameWork_JavaComp;

import JavaComp.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rubén
 */
public class ConsultaProductos extends javax.swing.JFrame {

    private TableRowSorter TRSFiltro;
    private OpcionesAdmin principal;

    /**
     * Creates new form ConsultaProductos
     *
     * @param ventana
     */
    public ConsultaProductos(OpcionesAdmin ventana) {
        JavaCompProductos.cargarDatos();
        principal = ventana;
        principal.setVisible(false);
        initComponents();
        this.setVisible(true);
        cargarImagenes();
        datosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Productos");
        setLocation(new java.awt.Point(500, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonAlta.setText("Alta Producto");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonBaja.setText("Baja Producto");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        JavaCompProductos.cargarDatos();
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "caracteristica", "categoria", "fecha Entrada", "calificacion", "precio", "stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable);

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
        });

        jLabel2.setText("Busqueda por nombre");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Componentes", "Ordenadores", "Moviles y telefonía", "TV,audio y foto", "Consolas y videojuegos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Busqueda por categoría");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 835, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(552, 552, 552)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButtonAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        JavaCompProductos.guardarDatos();
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        JavaCompProductos.guardarDatos();
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AltaProducto alta = new AltaProducto(this);
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tablaModel = (DefaultTableModel) ConsultaProductos.jTable.getModel();

        if (ConsultaProductos.jTable.getSelectedRow() != -1) {
            int fila = ConsultaProductos.jTable.getSelectedRow();
            String Titulo = ConsultaProductos.jTable.getValueAt(fila, 0).toString();

            if (JavaCompProductos.bajaProducto(JavaCompProductos.getProductosTitulo(Titulo))) {
                JOptionPane.showMessageDialog(this, "Producto Eliminado Correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                tablaModel.removeRow(fila);
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: ha ocurrido un error selecione el producto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
        ConsultaProductos.jTable.setModel(tablaModel);
        JavaCompProductos.guardarDatos();


    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        if (ConsultaProductos.jTable.getSelectedRow() != -1) {
            ModificarProducto modificar = new ModificarProducto(this);
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: ha ocurrido un error selecione el producto", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed
        // TODO add your handling code here:
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                FiltroNombre();
            }
        });
        TRSFiltro = new TableRowSorter(ConsultaProductos.jTable.getModel());
        ConsultaProductos.jTable.setRowSorter(TRSFiltro);
    }//GEN-LAST:event_txtFiltroKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tablaModel = (DefaultTableModel) ConsultaProductos.jTable.getModel();
        for (int i = 0; i < ConsultaProductos.jTable.getRowCount(); i++) {
            tablaModel.removeRow(i);
            i -= 1;
        }
        ConsultaProductos.jTable.setModel(new DefaultTableModel());
        JavaCompProductos.getProductos().stream().forEach((ProductoVenta producto) -> {
            try {
                if (jComboBox1.getSelectedIndex() == 0) {
                    tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio(), producto.getStock()});
                } else if (jComboBox1.getSelectedIndex() == 1 && "Componentes".equals(producto.getCategoria())) {
                    tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio(), producto.getStock()});
                } else if (jComboBox1.getSelectedIndex() == 2 && "Ordenadores".equals(producto.getCategoria())) {
                    tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio(), producto.getStock()});

                } else if (jComboBox1.getSelectedIndex() == 3 && "Moviles y telefonía".equals(producto.getCategoria())) {
                    tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio(), producto.getStock()});

                } else if (jComboBox1.getSelectedIndex() == 4 && "TV,audio y foto".equals(producto.getCategoria())) {
                    tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio(), producto.getStock()});

                } else if (jComboBox1.getSelectedIndex() == 5 && "Consolas y videojuegos".equals(producto.getCategoria())) {
                    tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio(), producto.getStock()});
                }
                //Asociar el modelo de lista al JList
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            ConsultaProductos.jTable.setModel(tablaModel);
        }
        );
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private void datosTabla() {
        DefaultTableModel tablaModel = (DefaultTableModel) ConsultaProductos.jTable.getModel();
        JavaCompProductos.getProductos().stream().forEach((ProductoVenta producto) -> {
            try {
                tablaModel.addRow(new Object[]{producto.getTitulo(), producto.getCaracteristicas(), producto.getCategoria(), producto.getFechaEntrada(), producto.getOpiniones().getCalificacion(), producto.getPrecio() + " €", producto.getStock()});

//Asociar el modelo de lista al JList
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            ConsultaProductos.jTable.setModel(tablaModel);
        }
        );
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tablaModel);
        ConsultaProductos.jTable.setRowSorter(sorter);
    }

    /**
     *
     */
    public void FiltroNombre() {
        int columnaTabla = 0; //la columna del nombre
        TRSFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + txtFiltro.getText(), columnaTabla));
    }
    private void cargarImagenes() {
        //logo
        ImageIcon logo1 = new ImageIcon("images/logo.png");
        ImageIcon logo = new ImageIcon(logo1.getImage());

        jLabel1.setIcon(logo);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
