/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameWork_JavaComp;

import JavaComp.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rubén
 */
public class ConsultaUsuarios extends javax.swing.JFrame {

    private TableRowSorter TRSFiltro;
    private OpcionesAdmin principal;

    /**
     * Creates new form ConsultaUsuarios2
     * @param ventana
     */
    public ConsultaUsuarios(OpcionesAdmin ventana) {
        JavaCompPersonas.cargarDatos();
        principal = ventana;
        principal.setVisible(false);
        initComponents();
        this.setVisible(true);
        cargarImagenes();
        datosTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ButtonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBaja = new javax.swing.JButton();
        ButtonVisualizar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextPane1.setToolTipText("Salia del programa");
        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Usuarios");
        setLocation(new java.awt.Point(500, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ButtonVolver.setText("Volver");
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "correo electronico", "telefono", "calle", "numero", "codigo postal", "ciudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButtonBaja.setText("Baja Persona");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        ButtonVisualizar.setText("Visualizar informacion");
        ButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVisualizarActionPerformed(evt);
            }
        });

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
        });

        jLabel2.setText("Busqueda por Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(ButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_ButtonVolverActionPerformed

    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tablaModel = (DefaultTableModel) ConsultaUsuarios.jTable1.getModel();

        if (ConsultaUsuarios.jTable1.getSelectedRow() != -1) {
            int fila = ConsultaUsuarios.jTable1.getSelectedRow();
            String Titulo = ConsultaUsuarios.jTable1.getValueAt(fila, 1).toString();
            Cliente cliente = JavaCompPersonas.getPersonasTitulo(Titulo);

            if (JavaCompPersonas.bajaPersona(cliente)) {
                JOptionPane.showMessageDialog(this, "Usuario Eliminado Correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                tablaModel.removeRow(fila);
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: ha ocurrido un error seleccione el Usuario", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
        ConsultaUsuarios.jTable1.setModel(tablaModel);
        JavaCompPersonas.guardarDatos();

    }//GEN-LAST:event_jButtonBajaActionPerformed

    private void ButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVisualizarActionPerformed
        // TODO add your handling code here:
        if (ConsultaUsuarios.jTable1.getSelectedRow() != -1) {
            int fila = ConsultaUsuarios.jTable1.getSelectedRow();
            String Titulo = ConsultaUsuarios.jTable1.getValueAt(fila, 1).toString();
            Cliente cliente = JavaCompPersonas.getPersonasTitulo(Titulo);

            if (cliente.getClass().getSimpleName().equals("ClienteParticular")) {
                PantallaRegistroParticular particular = new PantallaRegistroParticular(this);
            } else if (cliente.getClass().getSimpleName().equals("ClienteEmpresas")) {
                PantallaRegistroEmpresas empresa = new PantallaRegistroEmpresas(this);
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: ha ocurrido un error selecione el Usuario", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ButtonVisualizarActionPerformed

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed
        // TODO add your handling code here:
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                FiltroNombre();
            }
        });
        TRSFiltro = new TableRowSorter(ConsultaUsuarios.jTable1.getModel());
        ConsultaUsuarios.jTable1.setRowSorter(TRSFiltro);
    }//GEN-LAST:event_txtFiltroKeyPressed
    private void datosTabla() {
        DefaultTableModel tablaModel = (DefaultTableModel) ConsultaUsuarios.jTable1.getModel();
        JavaCompPersonas.getPersonas().stream().forEach((Cliente cliente) -> {
            try {

                tablaModel.addRow(new Object[]{cliente.getNombre(), cliente.getCorreoElectronico(), cliente.getTelefono(), cliente.getDireccion().getCalle(), cliente.getDireccion().getNumero(), cliente.getDireccion().getCodigoPostal(), cliente.getDireccion().getCiudad()});

//Asociar el modelo de lista al JList
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            ConsultaUsuarios.jTable1.setModel(tablaModel);
        }
        );
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tablaModel);
        ConsultaUsuarios.jTable1.setRowSorter(sorter);
    }

    /**
     *
     */
    public void FiltroNombre() {
        int columnaTabla = 0; //la columna del nombre
        TRSFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + txtFiltro.getText(), columnaTabla));
    }
    
        private void cargarImagenes() {
        //logo
        ImageIcon logo1 = new ImageIcon("images/logo.png");
        ImageIcon logo = new ImageIcon(logo1.getImage());

        jLabel1.setIcon(logo);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonVisualizar;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
