/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameWork_JavaComp;

import JavaComp.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rubén
 */
public class OpinarProducto extends javax.swing.JFrame {

    private ProductoVenta ve = null;
    private OpcionesCliente principal;

    /**
     * Creates new form OpinarProducto
     * @param ventana
     */
    public OpinarProducto(OpcionesCliente ventana) {
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        initComponents();
        cargarImagenes();
        int fila = OpcionesCliente.jTable.getSelectedRow();
        
        //ve=JavaCompProductos.ModificarProducto(fila);
        String Titulo=OpcionesCliente.jTable.getValueAt(fila,0).toString();
        
        ve=JavaCompProductos.getProductosTitulo(Titulo);
        String comentario = ve.getOpiniones().getComentario();
        int calificacion = ve.getOpiniones().getCalificacion();

        AreaComentario.setText(comentario);
        switch (calificacion) {
            case 1 ->
                jComboBox1.setSelectedIndex(0);
            case 2 ->
                jComboBox1.setSelectedIndex(1);
            case 3 ->
                jComboBox1.setSelectedIndex(2);
            case 4 ->
                jComboBox1.setSelectedIndex(3);
            case 5 ->
                jComboBox1.setSelectedIndex(4);
            default -> {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ButtonRealizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaComentario = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Calificación");

        jLabel2.setText("Comentario");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        ButtonRealizar.setText("Realizar Opinion");
        ButtonRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRealizarActionPerformed(evt);
            }
        });

        AreaComentario.setColumns(20);
        AreaComentario.setRows(5);
        jScrollPane1.setViewportView(AreaComentario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(ButtonRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRealizar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        JavaCompProductos.cargarDatos();
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void ButtonRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRealizarActionPerformed
        // TODO add your handling code here:
        String Calificacion = "";
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                Calificacion = "1";
                break;
            case 1:
                Calificacion = "2";
                break;
            case 2:
                Calificacion = "3";
                break;
            case 3:
                Calificacion = "4";
                break;
            case 4:
                Calificacion = "5";
                break;
            default:
                break;
        }
        String comentario = AreaComentario.getText();
        JOptionPane.showMessageDialog(this, "producto modificado correctamente.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        JavaCompProductos.guardarProductoModificado(ve, ve.getTitulo(), ve.getCaracteristicas(), ve.getCategoria(), ve.getPrecio(), ve.getStock(), ve.getFechaEntrada(), comentario, Integer.parseInt(Calificacion));
        this.setVisible(false);
        principal.setVisible(true);   
        JavaCompProductos.guardarDatos();
    }//GEN-LAST:event_ButtonRealizarActionPerformed
    private void cargarImagenes() {
        //logo
        ImageIcon logo1 = new ImageIcon("images/logo.png");
        ImageIcon logo = new ImageIcon(logo1.getImage());

        jLabel3.setIcon(logo);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaComentario;
    private javax.swing.JButton ButtonRealizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
