/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrameWork_JavaComp;

import JavaComp.*;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rubén
 */
public class PantallaCompra extends javax.swing.JFrame {

    /**
     *
     */
    public String salida = new String();
    private CantidadProducto principal;

    /**
     * Creates new form PantallaCompra
     *
     * @param ventana
     * @throws java.io.IOException
     */
    public PantallaCompra(CantidadProducto ventana) throws IOException {
        JavaCompPersonas.cargarDatos();
        JavaCompProductos.cargarDatos();
        principal = ventana;
        principal.setVisible(false);
        initComponents();
        this.setVisible(true);
        cargarImagenes();
        int value = (Integer) CantidadProducto.jSpinner1.getValue();
        String correo = PantallaInicio.FieldCorreoElectronico.getText();
        String clave = PantallaInicio.FieldContraseña.getText();
        //obtenemos el objeto del cliente
        Cliente login = JavaCompPersonas.encontrarCliente2(correo, clave);
        int fila = OpcionesCliente.jTable.getSelectedRow();
        String Titulo = OpcionesCliente.jTable.getValueAt(fila, 0).toString();
        //obtenemos el objeto necesario del producto
        ProductoVenta producto = JavaCompProductos.getProductosTitulo(Titulo);
        // este metodo crea la factura necesaria

        Double precio = (producto.getPrecio() * value) + 5;
        salida = salida.concat("-------------------------------- Factura de Compra JavaComp --------------------------------");
        salida = salida.concat("\n");
        salida = salida.concat("Hora de emision de la factura: " + LocalDate.now());
        salida = salida.concat("\n");
        salida = salida.concat("nombre: " + login.getNombre());
        salida = salida.concat("\n");
        salida = salida.concat("correo electronico: " + login.getCorreoElectronico());
        salida = salida.concat("\n");
        salida = salida.concat("direccion: ( " + login.getDireccion().toString());
        salida = salida.concat("\n");
        salida = salida.concat("Tfno: " + login.getTelefono());
        salida = salida.concat("\n");

        if (login.getClass().getSimpleName().equals("ClienteParticular")) {
            ClienteParticular alu = (ClienteParticular) login;
            salida = salida.concat("*** Cliente Particular ***");
            salida = salida.concat("\n");
            salida = salida.concat("Dni: " + alu.getDNI());
        } else {
            ClienteEmpresas pro = (ClienteEmpresas) login;
            salida = salida.concat("*** Cliente Empresas ***");
            salida = salida.concat("\n");
            salida = salida.concat("CIF: " + pro.getCIF());
            salida = salida.concat("\n");
            salida = salida.concat("web: " + pro.getWeb());
        }
        salida = salida.concat("\n");
        salida = salida.concat("-------------------------------- Datos del Producto --------------------------------");
        salida = salida.concat("\n");
        salida = salida.concat("nombre Producto:" + producto.getTitulo());
        salida = salida.concat("\n");
        salida = salida.concat("caracteristicas: " + producto.getCaracteristicas());
        salida = salida.concat("\n");
        salida = salida.concat("categoria: " + producto.getCategoria());
        salida = salida.concat("\n");
        salida = salida.concat("Calificación: " + producto.getOpiniones().getCalificacion());
        salida = salida.concat("\n");
        salida = salida.concat("Comentario: " + producto.getOpiniones().getComentario());
        salida = salida.concat("\n");
        salida = salida.concat("Precio de la compra total de los producto/s: " + producto.getPrecio() * value + "€");
        salida = salida.concat("\n");
        salida = salida.concat("Precio + gastos envío: " + precio + "€");
        salida = salida.concat("\n");
        salida = salida.concat("-------------------------------------------------------------------------------");

        jTextPane1.setText(salida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonCancelar = new javax.swing.JButton();
        ButtonComprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar Compra");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        ButtonComprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonComprar.setText("Realizar Compra");
        ButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComprarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextPane1.setToolTipText("Salia del programa");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(ButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(ButtonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 444, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(ButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void ButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComprarActionPerformed
        // TODO add your handling code here:
        int value = (Integer) CantidadProducto.jSpinner1.getValue();
        String correo = PantallaInicio.FieldCorreoElectronico.getText();
        String clave = PantallaInicio.FieldContraseña.getText();
        //obtenemos el objeto del cliente
        Cliente login = JavaCompPersonas.encontrarCliente2(correo, clave);

        DefaultTableModel tablaModel = (DefaultTableModel) OpcionesCliente.jTable.getModel();
        int fila = OpcionesCliente.jTable.getSelectedRow();
        String Titulo = OpcionesCliente.jTable.getValueAt(fila, 0).toString();
        //obtenemos el objeto necesario del producto
        ProductoVenta producto = JavaCompProductos.getProductosTitulo(Titulo);

        if (value < producto.getStock()) {
            producto.setStock(producto.getStock() - value);
            JOptionPane.showMessageDialog(this, "Producto Comprado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            String stock = String.valueOf(producto.getStock());
            CantidadProducto.jLabel4.setText(stock);
            CantidadProducto.jSpinner1.setValue(0);
            OpcionesCliente.jTable.setValueAt(producto.getStock(), fila, 6);
            this.setVisible(false);
            principal.setVisible(true);
            Venta ventaHecha = new Venta(producto, login);
            ventaHecha.setCantidad(value);
            JavaCompVentas.altaVenta(ventaHecha);

        } else if (value == producto.getStock()) {
            tablaModel.removeRow(fila);
            JavaCompProductos.bajaProducto(producto);
            CantidadProducto.jLabel4.setText("no queda Stock, Reponeremos pronto.");
            CantidadProducto.jSpinner1.setValue(0);
            JOptionPane.showMessageDialog(this, "Producto Comprado, NO QUEDA MAS STOCK DEL PRODUCTO", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            principal.setVisible(true);
            Venta ventaHecha = new Venta(producto, login);
            ventaHecha.setCantidad(value);
            JavaCompVentas.altaVenta(ventaHecha);

        } else {
            JOptionPane.showMessageDialog(this, "ERROR: ha ocurrido un error con la compra", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
            principal.setVisible(true);
        }
        try {
            JavaCompProductos.generaFactura(login, producto, value);
        } catch (IOException ex) {
            Logger.getLogger(PantallaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        JavaCompVentas.guardarDatos();
        JavaCompProductos.guardarDatos();
        OpcionesCliente.jTable.setModel(tablaModel);
    }//GEN-LAST:event_ButtonComprarActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarImagenes() {
        //logo
        ImageIcon logo1 = new ImageIcon("images/logo.png");
        ImageIcon logo = new ImageIcon(logo1.getImage());

        jLabel1.setIcon(logo);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
